### ISSUE TITLE
Short name?

### ISSUE THREAD

**Issue by isaced** [Dcard/DictionaryLiteralShorthandMacro#1]
Great project, could `#dictionaryLiteralShorthand()` be made shorter for readability and convenience?

 Here are some examples:

- `#dic()`
- `#dictLiteral()`
- `#makeDict()`

In a real code, it looks like this:

```swift
import DictionaryLiteralShorthand

let a = 99
let b = "foo"
let dictionary: [AnyHashable: Any] = #dic(a, b)
```

**Comment by JohnnyTseng** [comment]
Hey @isaced, sorry for late reply, I just recovered from COVID

Thanks for the suggestion! 
A shorter name does help developers, I'll discuss with my teammates which options would be best for a shorter name (I'll keep the original one and add a shorter one)

**Comment by JohnnyTseng** [comment]
Hi @isaced , we've renamed `#dictionaryLiteralShorthand` to `#dict`, thanks for your suggestion! 🙂
